### ISSUE TITLE
Can you avoid to use reloadData?

### ISSUE THREAD

**Issue by Ying1986** [nunobaldaia/NBReorderTableView#1]
Dear @nunobaldaia 

Your code is very good.
It is simple and useful.

I want to only remove reloadData and use other functions. (insertRows or deleteRows - beginUpdate/EndUpdate)

http://stackoverflow.com/questions/3945842/self-tableview-reloaddata-causing-crash-in-uitableview

Sometimes, reloadData is cause of crash error while tableview's dataSource change real-time.

I hope that you will fix this issue.

Thank you.

PS: I have change your code for test.

Please check this and let me see your opinion.

[NBReorderTableView_m.txt](https://github.com/nunobaldaia/NBReorderTableView/files/55329/NBReorderTableView_m.txt)

**Comment by nunobaldaia** [comment]
Hy Ying,

Sorry for taking so long to reply to you. I've just did a maintenance update (0.1.3) that removes the call to `reloadData`. And I don't think it needs to be replaced by anything else. It should be the controller's responsibility to ensure that the dataSource's consistency. Please let me know if this works for you.

Thanks!
Nuno
