### ISSUE TITLE
I can't set disable state-drag

### ISSUE THREAD

**Issue by Ying1986** [nunobaldaia/NBReorderTableView#2]
@nunobaldaia 
Thank you reply.

I have some issue while check your library.

https://github.com/nunobaldaia/NBReorderTableView/blob/a408fd26f8b1b4e39f420fe2a1f3c9c4ba32a973/Example/NBReorderTableView/NBViewController.m#L55

When return 'NO' from following function of NBViewController:
- (BOOL)tableView:(UITableView *)tableView canMoveRowAtIndexPath:(NSIndexPath *)indexPath

In this case drag is enable.

Please check again.

**Comment by nunobaldaia** [comment]
Hi Ying,

I removed the example project (on v0.1.4) since I don't have enough time resources to maintain it for now. Anyhow, if your data source returns false on `canMoveRowAtIndexPath:` delegate method the long press gesture recogniser will not be allowed to begin: https://github.com/nunobaldaia/NBReorderTableView/blob/master/NBReorderTableView/NBReorderTableView.m#L83-L93

Hope this helps.

**Comment by Ying1986** [comment]
@nunobaldaia 

I think you have mistakes.
What I mean is that your library is impossible to disable drag via :(BOOL)tableView:(UITableView *)tableView canMoveRowAtIndexPath:(NSIndexPath *)indexPath

And I can't understand why you removed sample project.
If sample project has error, how can you confirm canMoveRowAtIndexPath: is fine on the other projects?

Let me see your option.

**Comment by nunobaldaia** [comment]
I'm using this lib in production for a long time and I can confirm that this is not an issue. If you set your view controller as the data source of the table view it will disable the gesture recogniser if you return false on your `canMoveRowAtIndexPath:` please confirm that your `canMoveRowAtIndexPath:` is called.

I've not removed the demo project because this issue. I've removed it because it was outdated and I don't have time to maintain it.

**Comment by Ying1986** [comment]
@nunobaldaia 

Hello,
I have check your sample code it has only 1 function, 3 - Table view data source delegate methods, 2 #pragma mark - Table view delegate method, and only 95 lines (NBViewController).

I can't understand what is outdated?

Perhaps, project setting is updated, but NBViewController is not outdated. (It has some warnings on my Xcode 7.2).

Why you do think it may be not fine in your sample project?
I think it means this library has that issue.

PLEASE CHECK ON YOUR SAMPLE PROJECT, why canMoveRowAtIndexPath: is not fine.
Sorry.

**Comment by nunobaldaia** [comment]
Again, I removed my demo project because I was not able to run it. But let's do this if you agree: please send me a demo project that I can run on Xcode 7.2 and I'll take a look and see why it's not working for you.

**Comment by Ying1986** [comment]
@nunobaldaia 

I have attached sample project.
[NBReorderTableView-master.zip](https://github.com/nunobaldaia/NBReorderTableView/files/94584/NBReorderTableView-master.zip)

**Comment by Ying1986** [comment]
@nunobaldaia 

I have find the reason about this.

https://github.com/nunobaldaia/NBReorderTableView/blob/ab40b2a5fc64ab98a8075488b5a29dd88121081f/NBReorderTableView/NBReorderTableView.m#L85

This condition is false first time.

Please check it on the sample project.

**Comment by nunobaldaia** [comment]
You're right! The view controller was instantiating two table views :).

Instantiate the table view like this instead:

```
self.tableView = [[NBReorderTableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain];
```

It will fix the problem.

PS: This is why I have removed the example code. The lib is ok.

**Comment by Ying1986** [comment]
@nunobaldaia 

How about fix as following:
- (void)initialize
  {
  if (self.longPressGestureRecognizer == nil) {
      UILongPressGestureRecognizer *longPressGestureRecognizer = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(longPressGestureRecognized:)];
      longPressGestureRecognizer.delegate = self;
      [self addGestureRecognizer:longPressGestureRecognizer];
  
  ```
  self.longPressGestureRecognizer = longPressGestureRecognizer;
  ```
  
  }
  }

**Comment by nunobaldaia** [comment]
Ying, there's no need to fix. The demo project had some issues on creating the table view. Just specify the table view class (`NBReorderTableView`) on the storyboard or create it in code as I mentioned before (`[[NBReorderTableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain]`) and you'll be done :)
